services:
  app:
    env_file:
      - ./env/.env._local
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    environment:
      - NODE_OPTIONS=--max-old-space-size=6144
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "chmod +x /app/node_modules/.bin/* && yarn dev"
    networks:
      - default
      - data-platform-net
    ports:
      - 3002:3002
    tty: true

networks:
  data-platform-net:
    external: true
