services:
  app:
    env_file:
      - ./env/.env._local
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    environment:
      - NODE_OPTIONS=--max-old-space-size=6144
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "yarn dev"
    networks:
      - default
      - data-platform-net
    ports:
      - 3001:3001
    tty: true
    depends_on:
      - mock_server

  mock_server:
    build:
      context: ./docker/mock_server
      dockerfile: Dockerfile
    networks:
      - default
      - data-platform-net
    volumes:
      - .:/mock_server
      - ./docker/mock_server/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "4010:4010"
    command: sh -c 'sh /mock_server/docker/mock_server/entrypoint.sh'

networks:
  data-platform-net:
    external: true
